package com.brainuke.serenitydroid.util

import android.util.Base64
import org.json.JSONArray
import org.json.JSONObject
import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Encrypted Messageboard Sync Protocol Manager for Project Brainuke.
 *
 * Allows extracting dialogue & sensory interaction messageboard packets from SerenityDroid into
 * an encrypted JSON container (.bmb - Brainuke Message Board packet) or importing upgraded
 * response packs generated by Cecilia on PC Throne.
 */
object MessageBoardCrypto {

    private const val DEFAULT_PASSPHRASE = "SerenityBrainukeSharedThroneKey2025!"
    private const val GCM_IV_LENGTH = 12
    private const val GCM_TAG_LENGTH = 128

    data class ExportPacket(
        val sessionId: String,
        val appVersion: String = "1.0.0",
        val deviceName: String = "SerenityDroid Mobile",
        val exportedAt: Long = System.currentTimeMillis(),
        val turns: List<TurnData>
    )

    data class TurnData(
        val id: Long,
        val userInput: String,
        val thoughtStream: String,
        val finalResponse: String,
        val sourceDevice: String,
        val timestamp: Long
    )

    data class ImportResult(
        val importedCount: Int,
        val coreState: String,
        val CeciliaMessage: String
    )

    /**
     * Derives a 256-bit AES key from a passphrase using SHA-256.
     */
    private fun deriveKey(passphrase: String): SecretKeySpec {
        val digest = MessageDigest.getInstance("SHA-256")
        val keyBytes = digest.digest(passphrase.toByteArray(StandardCharsets.UTF_8))
        return SecretKeySpec(keyBytes, "AES")
    }

    /**
     * Exports dialogue turn list into an encrypted Base64 string payload with AES-GCM-256 authentication.
     */
    fun exportEncryptedPacket(packet: ExportPacket, passphrase: String = DEFAULT_PASSPHRASE): String {
        val jsonArray = JSONArray()
        packet.turns.forEach { turn ->
            val turnObj = JSONObject().apply {
                put("id", turn.id)
                put("user_input", turn.userInput)
                put("thought_stream", turn.thoughtStream)
                put("final_response", turn.finalResponse)
                put("source_device", turn.sourceDevice)
                put("timestamp", turn.timestamp)
            }
            jsonArray.put(turnObj)
        }

        val rootJson = JSONObject().apply {
            put("type", "brainuke_messageboard_packet")
            put("session_id", packet.sessionId)
            put("app_version", packet.appVersion)
            put("device_name", packet.deviceName)
            put("exported_at", packet.exportedAt)
            put("turns", jsonArray)
        }

        val plainBytes = rootJson.toString().toByteArray(StandardCharsets.UTF_8)
        val secretKey = deriveKey(passphrase)

        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv

        val cipherText = cipher.doFinal(plainBytes)

        // Envelope: IV (12 bytes) + CipherText
        val envelope = ByteArray(iv.size + cipherText.size)
        System.arraycopy(iv, 0, envelope, 0, iv.size)
        System.arraycopy(cipherText, 0, envelope, iv.size, cipherText.size)

        return Base64.encodeToString(envelope, Base64.DEFAULT)
    }

    /**
     * Decrypts and parses an encrypted messageboard packet payload into an ExportPacket.
     */
    fun decryptPacket(encryptedBase64: String, passphrase: String = DEFAULT_PASSPHRASE): ExportPacket {
        val envelope = Base64.decode(encryptedBase64, Base64.DEFAULT)
        if (envelope.size <= GCM_IV_LENGTH) {
            throw IllegalArgumentException("Invalid encrypted payload size")
        }

        val iv = ByteArray(GCM_IV_LENGTH)
        val cipherText = ByteArray(envelope.size - GCM_IV_LENGTH)

        System.arraycopy(envelope, 0, iv, 0, GCM_IV_LENGTH)
        System.arraycopy(envelope, GCM_IV_LENGTH, cipherText, 0, cipherText.size)

        val secretKey = deriveKey(passphrase)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)

        val plainBytes = cipher.doFinal(cipherText)
        val jsonStr = String(plainBytes, StandardCharsets.UTF_8)

        val root = JSONObject(jsonStr)
        val turnsArray = root.optJSONArray("turns") ?: JSONArray()

        val turnList = mutableListOf<TurnData>()
        for (i in 0 until turnsArray.length()) {
            val t = turnsArray.getJSONObject(i)
            turnList.add(
                TurnData(
                    id = t.optLong("id", System.currentTimeMillis()),
                    userInput = t.optString("user_input"),
                    thoughtStream = t.optString("thought_stream"),
                    finalResponse = t.optString("final_response"),
                    sourceDevice = t.optString("source_device", "android"),
                    timestamp = t.optLong("timestamp", System.currentTimeMillis())
                )
            )
        }

        return ExportPacket(
            sessionId = root.optString("session_id", "session_ext"),
            appVersion = root.optString("app_version", "1.0.0"),
            deviceName = root.optString("device_name", "Unknown"),
            exportedAt = root.optLong("exported_at", System.currentTimeMillis()),
            turns = turnList
        )
    }
}
